apiVersion: v1
kind: Pod
metadata:
  name: download-model-to-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: model-pvc
  restartPolicy: Never
  initContainers:
    - name: fix-volume-permissions
      image: quay.io/quay/busybox:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: ["sh"]
      args: ["-c", "chown -R 1001:1001 /mnt/models"]
      volumeMounts:
        - mountPath: "/mnt/models/"
          name: model-volume
  containers:
    - name: download-model
      image: registry.access.redhat.com/ubi9/python-311:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "1"
      command: ["sh"]
      args:
        - "-c"
        - |
          pip install --upgrade pip && pip install --upgrade huggingface_hub
          python3 -c "
          from huggingface_hub import snapshot_download
          snapshot_download(
              repo_id='${MODEL}',
              local_dir='/mnt/models/hf/instruction_tuned',
              local_dir_use_symlinks=False,
              use_auth_token='${HUGGING_FACE_HUB_TOKEN}'
          )"
      volumeMounts:
        - mountPath: "/mnt/models/"
          name: model-volume
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp
        - name: MODEL
          value: meta-llama/Meta-Llama-3-8B-Instruct
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hftoken
              key: token
