apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
